# -*- coding: utf-8 -*-
"""stock_project_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eK97ujex2c6H87B1XyN0iYGXx8rP5EEj
"""

# 1) install and import libraries

!pip install pandas pyyaml

import os

import yaml

import pandas as pd

import zipfile

# 2) extract zip

with zipfile.ZipFile('data.zip', 'r') as zip_ref:
    zip_ref.extractall()

# 3) verify folder structure

print(os.listdir())
print(os.listdir("data/"))

# 4) define paths

INPUT_FOLDER = "data/"
OUTPUT_FOLDER = "csv_output/"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# 5) Parse YAML + convert to dataframe

all_records = []

for root, _, files in os.walk(INPUT_FOLDER):
    for file in files:
        if file.endswith(".yaml"):
          with open(os.path.join(root, file)) as f:
             data = yaml.safe_load(f)


             for entry in data:
                 all_records.append({
                     "symbol": entry.get("Ticker"),
                     "date": entry.get("date"),
                     "month": entry.get("month"),
                     "open": entry.get("open"),
                     "high": entry.get("high"),
                     "low": entry.get("low"),
                     "close": entry.get("close"),
                     "volume": entry.get("volume")
                 })
df = pd.DataFrame(all_records)

print("data loaded")
print(df.head())

# 6) Data cleaning

# A) datetime format

df['date'] = pd.to_datetime(df['date'])

print(df['date'].dtype)

# creating year column

df['year'] = df['date'].dt.year

print(df.columns)

# re-ordering columns

df = df[['symbol', 'date', 'month', 'year', 'open', 'close', 'low', 'high', 'volume']]

print(df.columns)

# Transforming month column

df['month'] = df['date'].dt.strftime('%b')

df[['date', 'month']].head()

# B) Sorting symbol & date values

df.sample(10)

df = df.sort_values(['symbol', 'date'], ascending = [True, False])

df.head(10)

# C) drop duplicates

df = df.drop_duplicates()

df.duplicated().sum()

df.shape

# D) Handle missing values(remove or fill null values)

df.isnull().sum()

print("Data cleaned")
print("Total stocks:", df['symbol'].nunique())

# 7) Save CSV files (50 files)

for symbol, group in df.groupby('symbol'):
    group.to_csv(f"{OUTPUT_FOLDER}/{symbol}.csv", index = False)

print("CSV files created!")

# 8) Check output

os.listdir("csv_output")[:10]

# 9) Create zip file

import shutil
shutil.make_archive('csv_output', 'zip', 'csv_output')

# 9) Download csv files

from google.colab import files
files.download('csv_output.zip')