# -*- coding: utf-8 -*-
"""stock_insert.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qddBb0ZdtbfFHhl-vWwWUbqq0XSG61tG
"""

# 1) Import libraries

import sqlite3

import pandas as pd

import os

import zipfile

# 2) Extract zip

with zipfile.ZipFile('csv_output.zip', 'r') as zip_ref:
     zip_ref.extractall()

# 3) Create folder

os.makedirs("csv_output", exist_ok = True)

# 4) Move all csv files to one folder

import shutil

for file in os.listdir():
  if file.endswith('.csv'):
    shutil.move(file, f"csv_output/{file}")

os.listdir("csv_output")[:5]

# 5) create Database

conn = sqlite3.connect('stock.db')

cursor = conn.cursor()

# 6) Create Table

cursor.execute("""
CREATE TABLE IF NOT EXISTS stock_data (
  symbol TEXT,
  date TEXT,
  month TEXT,
  year INTEGER,
  open REAL,
  close REAL,
   low REAL,
   high REAL,
   volume INTEGER
)
""")

conn.commit()

# 7) Inserting Data into sqlite3 DB

for file in os.listdir("csv_output"):
  df = pd.read_csv(f"csv_output/{file}")
  df.to_sql('stock_data', conn, if_exists='append', index=False)

# 8) Verify Data inserted

pd.read_sql("SELECT COUNT(*) FROM stock_data", conn)