# -*- coding: utf-8 -*-
"""stock_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dec9uLYmrf5F9F0aWPMR_Pj-aBoYkFGQ
"""

# Extract zip file

import zipfile

with zipfile.ZipFile('csv_output.zip', 'r') as zip_ref:
     zip_ref.extractall('csv_output')

# load all CSVs

import os

import pandas as pd

all_df = []

for file in os.listdir('csv_output'):
    df = pd.read_csv(f"csv_output/{file}")
    all_df.append(df)

df = pd.concat(all_df, ignore_index=True)

# Load sector_data.csv file

sector_df = pd.read_csv("Sector_data - Sheet1.csv")

# Check it

print(sector_df.head())
print(sector_df.columns)

# Pandas is case-sensitive (rename column properly)

sector_df.rename(columns={'Symbol': 'symbol'}, inplace=True)

# Extra text - fix it

sector_df['symbol'] = sector_df['symbol'].str.split(':').str[-1].str.strip()

# Remove extra spaces

sector_df['symbol'] = sector_df['symbol'].str.strip()

df['symbol'] = df['symbol'].str.strip().str.upper()

sector_df['symbol'] = sector_df['symbol'].str.strip().str.upper()

# Key metrics

# Top 10 gainers and bottom 10 losers

def calculate_returns(df):
    df['return'] = (df['close'] - df['open']) / df['open']
    return df

df = calculate_returns(df)
print(df)

def top_gainers(df):
    return df.groupby('symbol')['return'].sum() \
             .sort_values(ascending=False).head(10)

gainers = top_gainers(df)
print("Top 10 gainers:")
print(gainers)

def top_losers(df):
    return df.groupby('symbol')['return'].sum() \
             .sort_values().head(10)
losers = top_losers(df)
print("bottom 10 losers:")
print(losers)

# Market summary

def market_summary(df):
    stock_return = df.groupby('symbol')['return'].sum()

    return {
        "green_stocks": (stock_return > 0).sum(),
        "red_stocks": (stock_return < 0).sum(),
        "avg_price": df['close'].mean(),
        "avg_volume": df['volume'].mean()
    }
summary = market_summary(df)
print("market_summary:")
print(summary)

# 1) Volatility Analysis

# Daily returns

def calculate_daily_returns(df):
    df = df.sort_values(['symbol', 'date'])
    df['daily_return'] = df.groupby('symbol')['close'].pct_change()
    return df

df = calculate_daily_returns(df)
print(df)

# Volatility

def calculate_volatility(df):
    volatility = df.groupby('symbol')['daily_return'].std()
    return volatility

vol = calculate_volatility(df)
print("stock volatility:")
print(vol)

# Top 10 + plot

def plot_top_volatility(volatility):
    top10 = volatility.sort_values(ascending=False).head(10)

    import matplotlib.pyplot as plt
    top10.plot(kind='bar')
    plt.title("Top 10 Most Volatile Stocks")
    plt.xlabel("stock")
    plt.ylabel("volatility")
    plt.show()

# Visualization (Top 10 most volatile stocks)

plot_top_volatility(vol)

# 2) Cumulative return over time

def cumulative_return(df):
    df = df.sort_values(['symbol', 'date'])

    df['daily_return'] = df.groupby('symbol')['close'].pct_change()

    df['cum_return'] = (1 + df['daily_return']).groupby(df['symbol']).cumprod()

    return df
df = cumulative_return(df)
print(df)

# Visualization (Top 5 cumulative returns)

def plot_top5_cumulative(df):
    top5 = df.groupby('symbol')['cum_return'].last() \
             .sort_values(ascending=False) \
             .head(5).index

    import matplotlib.pyplot as plt
    for stock in top5:
        temp = df[df['symbol'] == stock]
        plt.plot(temp['date'], temp['cum_return'], label=stock)
    plt.legend()
    plt.title("Top 5 Cumulative Returns")
    plt.xlabel("Date")
    plt.ylabel("Cumulative Return")
    plt.show()

plot_top5_cumulative(df)

# 3) Sector-wise Performance (merge sector data)

# Merge datasets

df = df.merge(sector_df[['symbol', 'sector']], on='symbol', how='left')

print(df)

def sector_performance(df):
    # df = df.merge(sector_df, on='symbol') # This merge is redundant as df already contains sector information

    sector_avg_return = df.groupby('sector')['return'].mean()

    return sector_avg_return
sector_performance = sector_performance(df)
print(sector_performance)

def plot_sector(sector_avg_return):
    import matplotlib.pyplot as plt
    sector_avg_return.plot(kind='bar')
    plt.title("Sector-wise Performance")
    plt.xlabel("Sector")
    plt.ylabel("Average Return")
    plt.show()

# Visualization (Average Yearly Return by Sector)

plot_sector(sector_performance)

# 4) Stock Price Correlation

def correlation_matrix(df):
    pivot = df.pivot(index='date', columns='symbol', values='close')
    return pivot.corr()

corr_matrix = correlation_matrix(df)
print(corr_matrix)

import matplotlib.pyplot as plt
import seaborn as sns

def plot_heatmap(corr_matrix):
    sns.heatmap(corr_matrix, cmap='coolwarm')
    plt.title("Stock Correlation Heatmap")
    plt.show()

# Visualizations (Stock Price Correlation Heatmap)

plot_heatmap(corr_matrix)

# 5) Top 5 Gainers and Losers (Month-wise)

import pandas as pd

def monthly_gainers_losers(df):
    df['date'] = pd.to_datetime(df['date'])
    df['month'] = df['date'].dt.to_period('M')

    # monthly first and last price
    monthly = df.groupby(['symbol', 'month']).agg(
        first_price=('close', 'first'),
        last_price=('close', 'last')
    )

    monthly['monthly_return'] = (
        (monthly['last_price'] - monthly['first_price']
    ) / monthly['first_price']
    ) * 100

    result = {}

    for m in monthly.index.get_level_values('month').unique():
        temp = monthly.xs(m, level='month')

        top5 = temp['monthly_return'].sort_values(ascending=False).head(5)
        bottom5 = temp['monthly_return'].sort_values().head(5)

        result[str(m)] = {
            "gainers": top5,
            "losers": bottom5
        }

    return result

res = monthly_gainers_losers(df)
print(res)

import matplotlib.pyplot as plt
import pandas as pd

def plot_monthly_dashboard(result):

    months = list(result.keys())

    fig, axes = plt.subplots(len(months), 1, figsize=(10, 40))

    for i, month in enumerate(months):

        gainers = result[month]['gainers']
        losers = result[month]['losers']

        combined = pd.concat([gainers, losers])

        colors = ['green' if x > 0 else 'red' for x in combined]

        combined.plot(
            kind='bar',
            ax=axes[i],
            color=colors
        )

        axes[i].set_title(f"{month} Top Gainers & Losers")

        axes[i].set_xlabel("Stocks")

        axes[i].set_ylabel("Monthly Return (%)")

    plt.tight_layout()

    plt.show()

# Visualization (Top 5 Gainers and Losers by Month)

plot_monthly_dashboard(res)

from google.colab import files
uploaded = files.upload()

import sqlite3

df['month'] = df['month'].astype(str)

conn = sqlite3.connect('stock.db')

df.to_sql(
    'stocks_analysis',
    conn,
    if_exists='replace',
    index=False
)

conn.close()

df.to_csv('cleaned_stock_data.csv', index=False)
print("Data exported successfully!")

print(df[['symbol', 'sector']].head(20))

print(sector_df['symbol'].unique())

# Complete Sector Mapping for 50 Stocks

sector_map = {

    # Miscellaneous
    'ADANIENT': 'MISCELLANEOUS',
    'ADANIPORTS': 'MISCELLANEOUS',
    'APOLLOHOSP': 'MISCELLANEOUS',

    # Paints
    'ASIANPAINT': 'PAINTS',

    # Banking
    'AXISBANK': 'BANKING',
    'HDFCBANK': 'BANKING',
    'ICICIBANK': 'BANKING',
    'INDUSINDBK': 'BANKING',
    'KOTAKBANK': 'BANKING',
    'SBIN': 'BANKING',

    # Automobiles
    'BAJAJ-AUTO': 'AUTOMOBILES',
    'EICHERMOT': 'AUTOMOBILES',
    'HEROMOTOCO': 'AUTOMOBILES',
    'M&M': 'AUTOMOBILES',
    'MARUTI': 'AUTOMOBILES',
    'TATAMOTORS': 'AUTOMOBILES',

    # Finance
    'BAJFINANCE': 'FINANCE',
    'BAJAJFINSV': 'FINANCE',
    'SHRIRAMFIN': 'FINANCE',

    # Defence
    'BEL': 'DEFENCE',

    # Telecom
    'BHARTIARTL': 'TELECOM',

    # Energy
    'BPCL': 'ENERGY',
    'IOC': 'ENERGY',
    'ONGC': 'ENERGY',
    'RELIANCE': 'ENERGY',

    # Pharmaceuticals
    'CIPLA': 'PHARMACEUTICALS',
    'DRREDDY': 'PHARMACEUTICALS',
    'SUNPHARMA': 'PHARMACEUTICALS',

    # Mining
    'COALINDIA': 'MINING',

    # Textiles
    'GRASIM': 'TEXTILES',

    # Software
    'HCLTECH': 'SOFTWARE',
    'INFY': 'SOFTWARE',
    'TCS': 'SOFTWARE',
    'TECHM': 'SOFTWARE',
    'WIPRO': 'SOFTWARE',

    # Insurance
    'HDFCLIFE': 'INSURANCE',
    'SBILIFE': 'INSURANCE',

    # Aluminium
    'HINDALCO': 'ALUMINIUM',

    # FMCG
    'HINDUNILVR': 'FMCG',
    'TATACONSUM': 'FMCG',

    # Food & Tobacco
    'ITC': 'FOOD & TOBACCO',
    'NESTLEIND': 'FOOD & TOBACCO',

    # Steel
    'JSWSTEEL': 'STEEL',
    'TATASTEEL': 'STEEL',

    # Engineering
    'LT': 'ENGINEERING',

    # Power
    'NTPC': 'POWER',
    'POWERGRID': 'POWER',

    # Retailing
    'TITAN': 'RETAILING',
    'TRENT': 'RETAILING',

    # Cement
    'ULTRACEMCO': 'CEMENT'
}

# Apply sector mapping
df['sector'] = df['symbol'].map(sector_map)

# Check output
print(df[['symbol', 'sector']].head(20))

# Save updated CSV
df.to_csv("cleaned_stock_data.csv", index=False)

print("Sector mapping completed successfully.")